// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: libs/grpc/src/auth/auth0.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "auth0";

export interface Auth0CreateUserResponse {
  userId: string;
}

export interface Auth0CreateUserDto {
  name: string;
  password: string;
  email: string;
}

export interface Auth0UpdateUserDto {
  auth0UserId: string;
  email: string;
  name: string;
}

export interface UserIdRequest {
  userId: string;
}

export interface Empty {
}

export const AUTH0_PACKAGE_NAME = "auth0";

export interface Auth0ServiceClient {
  createUser(request: Auth0CreateUserDto): Observable<Auth0CreateUserResponse>;

  updateUser(request: Auth0UpdateUserDto): Observable<Empty>;

  deleteUser(request: UserIdRequest): Observable<Empty>;
}

export interface Auth0ServiceController {
  createUser(
    request: Auth0CreateUserDto,
  ): Promise<Auth0CreateUserResponse> | Observable<Auth0CreateUserResponse> | Auth0CreateUserResponse;

  updateUser(request: Auth0UpdateUserDto): Promise<Empty> | Observable<Empty> | Empty;

  deleteUser(request: UserIdRequest): Promise<Empty> | Observable<Empty> | Empty;
}

export function Auth0ServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createUser", "updateUser", "deleteUser"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("Auth0Service", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("Auth0Service", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH0_SERVICE_NAME = "Auth0Service";
