include:
  - path: "./docker/monitoring.yaml"
  - path: "./docker/kong/kong-docker.yaml"
services:
  redis:
    image: redis/redis-stack:latest
    container_name: dms-redis
    ports:
      - "6379:6379"
      - "4000:8001"
    volumes:
      - dms_redis_data:/data
    restart: always
    networks:
      - dms_default

  auth_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dms-auth-service
    # ports:
    #   - 3002:3000
    env_file: ./apps/auth-service/.env
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    environment:
      PORT: 3002
      GRPC_PORT: 5002
      DB_HOST: postgres
    restart: unless-stopped
    command: pnpm start:dev auth-service
    networks:
      - dms_default

  # USER SERVICE
  user_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dms-user-service
    # ports:
    #   - 3003:3000
    env_file: ./apps/user-service/.env

    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    environment:
      PORT: 3003
      DB_HOST: user_service_db
      DB_NAME: user_service
    restart: unless-stopped
    command: pnpm start:dev user-service
    networks:
      - dms_default
      - user_service
    depends_on:
      - user_service_db

  user_service_db:
    image: postgres:16-alpine
    container_name: dms-user-service-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_service
    volumes:
      - user_service_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - user_service
  # USER SERVICE

  academic_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dms-academic-service
    # ports:
    #   - 3004:3000
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    env_file: ./apps/academic-service/.env
    environment:
      PORT: 3004
      DB_HOST: academic_service_db
      DB_NAME: academic_service
      BULL_REDIS_HOST: academic_redis
      CACHE_REDIS_HOST: academic_redis
    restart: unless-stopped
    command: pnpm start:dev academic-service
    networks:
      - dms_default
      - academic_service
    depends_on:
      - academic_service_db
      - academic_redis

  academic_service_db:
    image: postgres:16-alpine
    container_name: dms-academic-service-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: academic_service
    volumes:
      - academic_service_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - academic_service
  academic_redis:
    image: redis/redis-stack:latest
    container_name: dms-academic-redis
    volumes:
      - dms_academic_redis_data:/data
    restart: always
    networks:
      - academic_service
  register_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dms-register-service
    # ports:
    #   - 3005:3000
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    env_file: ./apps/register-service/.env
    environment:
      PORT: 3005
      DB_HOST: register_service_db
      DB_NAME: register_service
      BULL_REDIS_HOST: register_redis
      CACHE_REDIS_HOST: register_redis
    restart: unless-stopped
    command: pnpm start:dev register-service
    networks:
      - dms_default
      - register_service
    depends_on:
      - register_service_db
      - register_redis

  register_service_db:
    image: postgres:16-alpine
    container_name: dms-register-service-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: register_service
    volumes:
      - register_service_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - register_service
  register_redis:
    image: redis/redis-stack:latest
    container_name: dms-register-redis
    volumes:
      - dms_register_redis_data:/data
    restart: always
    networks:
      - register_service
  messenger_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dms-messenger-service
    # ports:
    #   - 3006:3000
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    env_file: ./apps/messenger-service/.env
    environment:
      PORT: 3006
      DB_HOST: messenger_service_db
      DB_NAME: messenger_service
      BULL_REDIS_HOST: messenger_redis
      CACHE_REDIS_HOST: messenger_redis
    restart: unless-stopped
    command: pnpm start:dev messenger-service
    networks:
      - dms_default
      - messenger_service
    depends_on:
      - messenger_service_db
      - messenger_redis

  messenger_service_db:
    image: postgres:16-alpine
    container_name: dms-messenger-service-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: messenger_service
    volumes:
      - messenger_service_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - messenger_service
  messenger_redis:
    image: redis/redis-stack:latest
    container_name: dms-messenger-redis
    volumes:
      - dms_messenger_redis_data:/data
    restart: always
    networks:
      - messenger_service

  docs_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dms-docs-service
    # ports:
    #   - 3007:3000
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    environment:
      PORT: 3007
    restart: unless-stopped
    command: pnpm start:dev docs-service
    networks:
      - dms_default

volumes:
  dms_data:
  dms_redis_data:
  user_service_data:
  academic_service_data:
  dms_academic_redis_data:
  register_service_data:
  dms_register_redis_data:
  messenger_service_data:
  dms_messenger_redis_data:

networks:
  dms_default:
    driver: bridge
  user_service:
    driver: bridge
  academic_service:
    driver: bridge
  register_service:
    driver: bridge
  messenger_service:
    driver: bridge
