// src/database/seeds/course.data.ts

export const semesterIds = {
  sem1: 'a1593306-7fd2-453b-a34c-79c165a9380b',
  sem2: '19db3fcc-da9d-4539-bc77-c7b00d46cd60',
  sem3: '45268166-4d99-4f13-89e6-44a9c6a6af9a',
  sem4: 'd3e70279-1695-4085-a436-04ff30823843',
  sem5: '28069ac0-0c77-4695-a2d2-2e59686a2a37',
  sem6: 'cc03dffd-09f0-4b0f-883c-c58621a51d8c',
  sem7: 'f128676c-35b8-43fb-af04-ad77cf31fcad',
  sem8: '2d277274-a80c-4ba4-919b-91d992335b5f',
};

export const COURSES_SEED_DATA = [
  {
    semesterId: semesterIds.sem1,
    code: '21011',
    name: 'Engineering Drawing',
    theoryCredits: 0,
    practicalCredits: 6,
    credits: 2,
  },
  {
    semesterId: semesterIds.sem1,
    code: '25711',
    name: 'Bangla-I',
    theoryCredits: 2,
    practicalCredits: 0,
    credits: 2,
  },
  {
    semesterId: semesterIds.sem1,
    code: '25712',
    name: 'English-I',
    theoryCredits: 2,
    practicalCredits: 0,
    credits: 2,
  },
  {
    semesterId: semesterIds.sem1,
    code: '25911',
    name: 'Mathematics-I',
    theoryCredits: 3,
    practicalCredits: 3,
    credits: 4,
  },
  {
    semesterId: semesterIds.sem1,
    code: '25912',
    name: 'Physics-I',
    theoryCredits: 3,
    practicalCredits: 3,
    credits: 4,
  },
  {
    semesterId: semesterIds.sem1,
    code: '28511',
    name: 'Computer Office Application',
    theoryCredits: 0,
    practicalCredits: 6,
    credits: 2,
  },
  {
    semesterId: semesterIds.sem1,
    code: '26711',
    name: 'Basic Electricity',
    theoryCredits: 3,
    practicalCredits: 3,
    credits: 4,
  },

  // [cite_start]// --- 2nd Semester --- [cite: 7]
  {
    semesterId: semesterIds.sem2,
    code: '25721',
    name: 'Bangla-II',
    theoryCredits: 2,
    practicalCredits: 0,
    credits: 2,
  },
  {
    semesterId: semesterIds.sem2,
    code: '25722',
    name: 'English-II',
    theoryCredits: 2,
    practicalCredits: 0,
    credits: 2,
  },
  {
    semesterId: semesterIds.sem2,
    code: '25812',
    name: 'Physical Education & Life Skills Development',
    theoryCredits: 0,
    practicalCredits: 3,
    credits: 1,
  },
  {
    semesterId: semesterIds.sem2,
    code: '25913',
    name: 'Chemistry',
    theoryCredits: 3,
    practicalCredits: 3,
    credits: 4,
  },
  {
    semesterId: semesterIds.sem2,
    code: '25921',
    name: 'Mathematics-II',
    theoryCredits: 3,
    practicalCredits: 3,
    credits: 4,
  },
  {
    semesterId: semesterIds.sem2,
    code: '28521',
    name: 'Python Programming',
    theoryCredits: 2,
    practicalCredits: 3,
    credits: 3,
  },
  {
    semesterId: semesterIds.sem2,
    code: '28522',
    name: 'Computer Graphics Design-I',
    theoryCredits: 0,
    practicalCredits: 6,
    credits: 2,
  },
  {
    semesterId: semesterIds.sem2,
    code: '26811',
    name: 'Basic Electronics',
    theoryCredits: 2,
    practicalCredits: 3,
    credits: 3,
  },

  // [cite_start]// --- 3rd Semester --- [cite: 11]
  {
    semesterId: semesterIds.sem3,
    code: '25811',
    name: 'Social Science',
    theoryCredits: 2,
    practicalCredits: 0,
    credits: 2,
  },
  {
    semesterId: semesterIds.sem3,
    code: '25922',
    name: 'Physics-II',
    theoryCredits: 3,
    practicalCredits: 3,
    credits: 4,
  },
  {
    semesterId: semesterIds.sem3,
    code: '25931',
    name: 'Mathematics-III',
    theoryCredits: 3,
    practicalCredits: 3,
    credits: 4,
  },
  {
    semesterId: semesterIds.sem3,
    code: '28531',
    name: 'Application Development Using Python',
    theoryCredits: 2,
    practicalCredits: 3,
    credits: 3,
  },
  {
    semesterId: semesterIds.sem3,
    code: '28532',
    name: 'Computer Graphics Design-II',
    theoryCredits: 0,
    practicalCredits: 3,
    credits: 1,
  },
  {
    semesterId: semesterIds.sem3,
    code: '28533',
    name: 'IT Support Services',
    theoryCredits: 2,
    practicalCredits: 6,
    credits: 4,
  },
  {
    semesterId: semesterIds.sem3,
    code: '26831',
    name: 'Digital Electronics-I',
    theoryCredits: 2,
    practicalCredits: 3,
    credits: 3,
  },

  // [cite_start]// --- 4th Semester --- [cite: 14]
  {
    semesterId: semesterIds.sem4,
    code: '25831',
    name: 'Business Communication',
    theoryCredits: 2,
    practicalCredits: 0,
    credits: 2,
  },
  {
    semesterId: semesterIds.sem4,
    code: '28541',
    name: 'Java Programming',
    theoryCredits: 2,
    practicalCredits: 3,
    credits: 3,
  },
  {
    semesterId: semesterIds.sem4,
    code: '28542',
    name: 'Data Structure & Algorithm',
    theoryCredits: 2,
    practicalCredits: 3,
    credits: 3,
  },
  {
    semesterId: semesterIds.sem4,
    code: '28543',
    name: 'Computer Peripherals & Interfacing',
    theoryCredits: 3,
    practicalCredits: 3,
    credits: 4,
  },
  {
    semesterId: semesterIds.sem4,
    code: '28544',
    name: 'Web Design & Development-I',
    theoryCredits: 1,
    practicalCredits: 6,
    credits: 3,
  },
  {
    semesterId: semesterIds.sem4,
    code: '26841',
    name: 'Digital Electronics-II',
    theoryCredits: 2,
    practicalCredits: 3,
    credits: 3,
  },
  {
    semesterId: semesterIds.sem4,
    code: '29041',
    name: 'Environmental Studies',
    theoryCredits: 2,
    practicalCredits: 3,
    credits: 3,
  },

  // [cite_start]// --- 5th Semester --- [cite: 18]
  {
    semesterId: semesterIds.sem5,
    code: '25841',
    name: 'Accounting',
    theoryCredits: 2,
    practicalCredits: 0,
    credits: 2,
  },
  {
    semesterId: semesterIds.sem5,
    code: '28551',
    name: 'Application Development Using Java',
    theoryCredits: 2,
    practicalCredits: 3,
    credits: 3,
  },
  {
    semesterId: semesterIds.sem5,
    code: '28552',
    name: 'Web Design & Development-II',
    theoryCredits: 1,
    practicalCredits: 6,
    credits: 3,
  },
  {
    semesterId: semesterIds.sem5,
    code: '28553',
    name: 'Computer Architecture & Microprocessor',
    theoryCredits: 3,
    practicalCredits: 3,
    credits: 4,
  },
  {
    semesterId: semesterIds.sem5,
    code: '28554',
    name: 'Data Communication',
    theoryCredits: 3,
    practicalCredits: 3,
    credits: 4,
  },
  {
    semesterId: semesterIds.sem5,
    code: '28555',
    name: 'Operating System',
    theoryCredits: 2,
    practicalCredits: 3,
    credits: 3,
  },
  {
    semesterId: semesterIds.sem5,
    code: '28556',
    name: 'Project Work-I',
    theoryCredits: 0,
    practicalCredits: 6,
    credits: 2,
  },

  // [cite_start]// --- 6th Semester --- [cite: 21]
  {
    semesterId: semesterIds.sem6,
    code: '25851',
    name: 'Principles of Marketing',
    theoryCredits: 2,
    practicalCredits: 0,
    credits: 2,
  },
  {
    semesterId: semesterIds.sem6,
    code: '25852',
    name: 'Industrial Management',
    theoryCredits: 2,
    practicalCredits: 0,
    credits: 2,
  },
  {
    semesterId: semesterIds.sem6,
    code: '28561',
    name: 'Database Management System',
    theoryCredits: 2,
    practicalCredits: 3,
    credits: 3,
  },
  {
    semesterId: semesterIds.sem6,
    code: '28562',
    name: 'Computer Networking',
    theoryCredits: 2,
    practicalCredits: 3,
    credits: 3,
  },
  {
    semesterId: semesterIds.sem6,
    code: '28563',
    name: 'Sensor & IoT System',
    theoryCredits: 2,
    practicalCredits: 3,
    credits: 3,
  },
  {
    semesterId: semesterIds.sem6,
    code: '28564',
    name: 'Microcontroller Based System Design & Development',
    theoryCredits: 2,
    practicalCredits: 6,
    credits: 4,
  },
  {
    semesterId: semesterIds.sem6,
    code: '28565',
    name: 'Surveillance Security System',
    theoryCredits: 1,
    practicalCredits: 3,
    credits: 2,
  },
  {
    semesterId: semesterIds.sem6,
    code: '28566',
    name: 'Web Development Project',
    theoryCredits: 0,
    practicalCredits: 6,
    credits: 2,
  },

  // [cite_start]// --- 7th Semester --- [cite: 25]
  {
    semesterId: semesterIds.sem7,
    code: '25853',
    name: 'Innovation & Entrepreneurship',
    theoryCredits: 2,
    practicalCredits: 0,
    credits: 2,
  },
  {
    semesterId: semesterIds.sem7,
    code: '28571',
    name: 'Digital Marketing Technique',
    theoryCredits: 2,
    practicalCredits: 3,
    credits: 3,
  },
  {
    semesterId: semesterIds.sem7,
    code: '28572',
    name: 'Network Administration & Services',
    theoryCredits: 3,
    practicalCredits: 3,
    credits: 4,
  },
  {
    semesterId: semesterIds.sem7,
    code: '28573',
    name: 'Cyber Security & Ethics',
    theoryCredits: 2,
    practicalCredits: 3,
    credits: 3,
  },
  {
    semesterId: semesterIds.sem7,
    code: '28574',
    name: 'Apps Development Project',
    theoryCredits: 1,
    practicalCredits: 3,
    credits: 2,
  },
  {
    semesterId: semesterIds.sem7,
    code: '28575',
    name: 'Multimedia & Animation',
    theoryCredits: 2,
    practicalCredits: 3,
    credits: 3,
  },
  {
    semesterId: semesterIds.sem7,
    code: '28576',
    name: 'Project Work-II',
    theoryCredits: 0,
    practicalCredits: 6,
    credits: 2,
  },

  // [cite_start]// --- 8th Semester --- [cite: 28]
  {
    semesterId: semesterIds.sem8,
    code: '28582',
    name: 'Industrial Attachment',
    theoryCredits: 0,
    practicalCredits: 24,
    credits: 8,
  }, // Code manually assigned for uniqueness
  {
    semesterId: semesterIds.sem8,
    code: '28581',
    name: 'Project Presentation',
    theoryCredits: 0,
    practicalCredits: 12,
    credits: 4,
  },
];
