// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: libs/grpc/src/protos/semester.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "semester";

export interface SemesterResponse {
  id: string;
  name: string;
}

export interface SemesterIdRequest {
  id: string;
}

export interface Empty {
}

export const SEMESTER_PACKAGE_NAME = "semester";

export interface SemesterServiceClient {
  getSemesterById(request: SemesterIdRequest): Observable<SemesterResponse>;
}

export interface SemesterServiceController {
  getSemesterById(
    request: SemesterIdRequest,
  ): Promise<SemesterResponse> | Observable<SemesterResponse> | SemesterResponse;
}

export function SemesterServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getSemesterById"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("SemesterService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("SemesterService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const SEMESTER_SERVICE_NAME = "SemesterService";
