// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: libs/grpc/src/protos/student.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "student";

export interface StudentResponse {
  id: string;
  userId: string;
  enrolmentDate: string;
  status?: string | undefined;
  session: string;
  graduationYear?: number | undefined;
  currentSemesterId: string;
  currentSemester: string;
}

export interface StudentIdRequest {
  studentId: string;
}

export const STUDENT_PACKAGE_NAME = "student";

export interface StudentServiceClient {
  getStudentById(request: StudentIdRequest): Observable<StudentResponse>;
}

export interface StudentServiceController {
  getStudentById(request: StudentIdRequest): Promise<StudentResponse> | Observable<StudentResponse> | StudentResponse;
}

export function StudentServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getStudentById"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("StudentService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("StudentService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const STUDENT_SERVICE_NAME = "StudentService";
