services:
  kong:
    image: kong:latest
    container_name: kong-gateway
    restart: unless-stopped
    networks:
      - dms_default
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    healthcheck:
      test: ['CMD', 'kong', 'health']
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - '3000:8000'
      - '8001:8001'
      - '8002:8002'
      - '8443:8443'
      - '8444:8444'
    volumes:
      - ./kong.yaml:/usr/local/kong/declarative/kong.yml
