services:
  kong:
    # image: kong:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dms-kong-gateway
    restart: unless-stopped
    networks:
      - dms_default
    env_file: .env
    environment:
      KONG_DATABASE: 'off'
      KONG_LUA_SHARED_DICT: 'jwks_cache 15m'
      KONG_PLUGINS: 'bundled, jwt-keycloak'
      KONG_DECLARATIVE_CONFIG: /tmp/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_ENV_VARS: AUTH0_DOMAIN
    healthcheck:
      test: ['CMD', 'kong', 'health']
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - '3000:8000'
      - '8001:8001'
      - '8002:8002'
      - '8443:8443'
      - '8444:8444'
    volumes:
      # Mount as a template instead of directly as the config file
      - ./kong.yaml:/usr/local/kong/declarative/kong.yml.template
    # Run envsubst to replace ${AUTH0_DOMAIN} before starting kong (saving to /tmp/ to avoid permission errors)
    command: /bin/sh -c "envsubst < /usr/local/kong/declarative/kong.yml.template > /tmp/kong.yml && /docker-entrypoint.sh kong docker-start"
