// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: libs/grpc/src/protos/course/course-schedule.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "course_schedule";

export interface CourseScheduleResponse {
  id: string;
  courseId: string;
  dayOfWeek: string;
  startTime: string;
  endTime: string;
  room?: string | undefined;
  teacherId?: string | undefined;
}

export interface CourseScheduleIdRequest {
  id: string;
}

export const COURSE_SCHEDULE_PACKAGE_NAME = "course_schedule";

export interface CourseScheduleServiceClient {
  getCourseScheduleById(request: CourseScheduleIdRequest): Observable<CourseScheduleResponse>;
}

export interface CourseScheduleServiceController {
  getCourseScheduleById(
    request: CourseScheduleIdRequest,
  ): Promise<CourseScheduleResponse> | Observable<CourseScheduleResponse> | CourseScheduleResponse;
}

export function CourseScheduleServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getCourseScheduleById"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("CourseScheduleService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("CourseScheduleService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const COURSE_SCHEDULE_SERVICE_NAME = "CourseScheduleService";
